/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"


enum Aroma_ImageType {
  ImageType_JPEG = 1,
  ImageType_PNG = 2
};

enum Aroma_Industry {
  Industry_BANKING = 1,
  Industry_ECOMMERCE = 2,
  Industry_EDUCATION = 3,
  Industry_ENTERTAINMENT = 4,
  Industry_GOVERMENT = 5,
  Industry_MARKETING = 6,
  Industry_RETAIL = 7,
  Industry_TECH = 8,
  Industry_AEROSPACE = 9,
  Industry_ROBOTICS = 10
};

enum Aroma_Tier {
  Tier_FREE = 1,
  Tier_PAID = 2
};

enum Aroma_TimeUnit {
  TimeUnit_MILLIS = 1,
  TimeUnit_SECONDS = 2,
  TimeUnit_MINUTES = 3,
  TimeUnit_HOURS = 4,
  TimeUnit_DAYS = 5,
  TimeUnit_WEEKS = 6
};

enum Aroma_ProgrammingLanguage {
  ProgrammingLanguage_JAVA = 1,
  ProgrammingLanguage_CPP = 2,
  ProgrammingLanguage_C_SHARP = 3,
  ProgrammingLanguage_C = 4,
  ProgrammingLanguage_OBJECTIVE_C = 5,
  ProgrammingLanguage_SWIFT = 6,
  ProgrammingLanguage_DOT_NET = 7,
  ProgrammingLanguage_RUBY = 8,
  ProgrammingLanguage_GROOVY = 9,
  ProgrammingLanguage_PYTHON = 10,
  ProgrammingLanguage_PHP = 11,
  ProgrammingLanguage_NODE = 12,
  ProgrammingLanguage_DART = 13,
  ProgrammingLanguage_OTHER = 14
};

enum Aroma_Role {
  Role_DEVELOPER = 1,
  Role_OPERATIONS = 2,
  Role_MANAGER = 3,
  Role_PRODUCT = 4,
  Role_QA = 5,
  Role_FAN = 6
};

enum Aroma_Urgency {
  Urgency_LOW = 1,
  Urgency_MEDIUM = 2,
  Urgency_HIGH = 3
};

typedef int32_t Aroma_int;

typedef int64_t Aroma_long;

typedef int64_t Aroma_timestamp;

typedef NSString * Aroma_uuid;

@interface Aroma_LengthOfTime : NSObject <TBase, NSCoding> {
  int __unit;
  Aroma_long __value;

  BOOL __unit_isset;
  BOOL __value_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=unit, setter=setUnit:) int unit;
@property (nonatomic, getter=value, setter=setValue:) Aroma_long value;
#endif

- (id) init;
- (id) initWithUnit: (int) unit value: (Aroma_long) value;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) unit;
- (void) setUnit: (int) unit;
#endif
- (BOOL) unitIsSet;

#if !__has_feature(objc_arc)
- (Aroma_long) value;
- (void) setValue: (Aroma_long) value;
#endif
- (BOOL) valueIsSet;

@end

@interface Aroma_Dimension : NSObject <TBase, NSCoding> {
  Aroma_int __width;
  Aroma_int __height;

  BOOL __width_isset;
  BOOL __height_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=width, setter=setWidth:) Aroma_int width;
@property (nonatomic, getter=height, setter=setHeight:) Aroma_int height;
#endif

- (id) init;
- (id) initWithWidth: (Aroma_int) width height: (Aroma_int) height;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Aroma_int) width;
- (void) setWidth: (Aroma_int) width;
#endif
- (BOOL) widthIsSet;

#if !__has_feature(objc_arc)
- (Aroma_int) height;
- (void) setHeight: (Aroma_int) height;
#endif
- (BOOL) heightIsSet;

@end

@interface Aroma_Image : NSObject <TBase, NSCoding> {
  int __imageType;
  NSData * __data;
  Aroma_Dimension * __dimension;

  BOOL __imageType_isset;
  BOOL __data_isset;
  BOOL __dimension_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=imageType, setter=setImageType:) int imageType;
@property (nonatomic, retain, getter=data, setter=setData:) NSData * data;
@property (nonatomic, retain, getter=dimension, setter=setDimension:) Aroma_Dimension * dimension;
#endif

- (id) init;
- (id) initWithImageType: (int) imageType data: (NSData *) data dimension: (Aroma_Dimension *) dimension;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) imageType;
- (void) setImageType: (int) imageType;
#endif
- (BOOL) imageTypeIsSet;

#if !__has_feature(objc_arc)
- (NSData *) data;
- (void) setData: (NSData *) data;
#endif
- (BOOL) dataIsSet;

#if !__has_feature(objc_arc)
- (Aroma_Dimension *) dimension;
- (void) setDimension: (Aroma_Dimension *) dimension;
#endif
- (BOOL) dimensionIsSet;

@end

@interface Aroma_Message : NSObject <TBase, NSCoding> {
  Aroma_uuid __messageId;
  NSString * __body;
  int __urgency;
  Aroma_timestamp __timeOfCreation;
  Aroma_timestamp __timeMessageReceived;
  NSString * __applicationName;
  NSString * __hostname;
  NSString * __macAddress;
  BOOL __isTruncated;
  NSString * __title;
  Aroma_uuid __applicationId;
  NSString * __deviceName;

  BOOL __messageId_isset;
  BOOL __body_isset;
  BOOL __urgency_isset;
  BOOL __timeOfCreation_isset;
  BOOL __timeMessageReceived_isset;
  BOOL __applicationName_isset;
  BOOL __hostname_isset;
  BOOL __macAddress_isset;
  BOOL __isTruncated_isset;
  BOOL __title_isset;
  BOOL __applicationId_isset;
  BOOL __deviceName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=messageId, setter=setMessageId:) Aroma_uuid messageId;
@property (nonatomic, retain, getter=body, setter=setBody:) NSString * body;
@property (nonatomic, getter=urgency, setter=setUrgency:) int urgency;
@property (nonatomic, getter=timeOfCreation, setter=setTimeOfCreation:) Aroma_timestamp timeOfCreation;
@property (nonatomic, getter=timeMessageReceived, setter=setTimeMessageReceived:) Aroma_timestamp timeMessageReceived;
@property (nonatomic, retain, getter=applicationName, setter=setApplicationName:) NSString * applicationName;
@property (nonatomic, retain, getter=hostname, setter=setHostname:) NSString * hostname;
@property (nonatomic, retain, getter=macAddress, setter=setMacAddress:) NSString * macAddress;
@property (nonatomic, getter=isTruncated, setter=setIsTruncated:) BOOL isTruncated;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, retain, getter=applicationId, setter=setApplicationId:) Aroma_uuid applicationId;
@property (nonatomic, retain, getter=deviceName, setter=setDeviceName:) NSString * deviceName;
#endif

- (id) init;
- (id) initWithMessageId: (Aroma_uuid) messageId body: (NSString *) body urgency: (int) urgency timeOfCreation: (Aroma_timestamp) timeOfCreation timeMessageReceived: (Aroma_timestamp) timeMessageReceived applicationName: (NSString *) applicationName hostname: (NSString *) hostname macAddress: (NSString *) macAddress isTruncated: (BOOL) isTruncated title: (NSString *) title applicationId: (Aroma_uuid) applicationId deviceName: (NSString *) deviceName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Aroma_uuid) messageId;
- (void) setMessageId: (Aroma_uuid) messageId;
#endif
- (BOOL) messageIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) body;
- (void) setBody: (NSString *) body;
#endif
- (BOOL) bodyIsSet;

#if !__has_feature(objc_arc)
- (int) urgency;
- (void) setUrgency: (int) urgency;
#endif
- (BOOL) urgencyIsSet;

#if !__has_feature(objc_arc)
- (Aroma_timestamp) timeOfCreation;
- (void) setTimeOfCreation: (Aroma_timestamp) timeOfCreation;
#endif
- (BOOL) timeOfCreationIsSet;

#if !__has_feature(objc_arc)
- (Aroma_timestamp) timeMessageReceived;
- (void) setTimeMessageReceived: (Aroma_timestamp) timeMessageReceived;
#endif
- (BOOL) timeMessageReceivedIsSet;

#if !__has_feature(objc_arc)
- (NSString *) applicationName;
- (void) setApplicationName: (NSString *) applicationName;
#endif
- (BOOL) applicationNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hostname;
- (void) setHostname: (NSString *) hostname;
#endif
- (BOOL) hostnameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) macAddress;
- (void) setMacAddress: (NSString *) macAddress;
#endif
- (BOOL) macAddressIsSet;

#if !__has_feature(objc_arc)
- (BOOL) isTruncated;
- (void) setIsTruncated: (BOOL) isTruncated;
#endif
- (BOOL) isTruncatedIsSet;

#if !__has_feature(objc_arc)
- (NSString *) title;
- (void) setTitle: (NSString *) title;
#endif
- (BOOL) titleIsSet;

#if !__has_feature(objc_arc)
- (Aroma_uuid) applicationId;
- (void) setApplicationId: (Aroma_uuid) applicationId;
#endif
- (BOOL) applicationIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) deviceName;
- (void) setDeviceName: (NSString *) deviceName;
#endif
- (BOOL) deviceNameIsSet;

@end

@interface Aroma_Organization : NSObject <TBase, NSCoding> {
  Aroma_uuid __organizationId;
  NSString * __organizationName;
  NSString * __website;
  Aroma_Image * __logo;
  NSString * __techStack;
  NSMutableArray * __owners;
  NSString * __organizationEmail;
  NSString * __stockMarketSymbol;
  NSString * __logoLink;
  int __industry;
  int __tier;
  NSString * __organizationDescription;
  NSString * __githubProfile;

  BOOL __organizationId_isset;
  BOOL __organizationName_isset;
  BOOL __website_isset;
  BOOL __logo_isset;
  BOOL __techStack_isset;
  BOOL __owners_isset;
  BOOL __organizationEmail_isset;
  BOOL __stockMarketSymbol_isset;
  BOOL __logoLink_isset;
  BOOL __industry_isset;
  BOOL __tier_isset;
  BOOL __organizationDescription_isset;
  BOOL __githubProfile_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=organizationId, setter=setOrganizationId:) Aroma_uuid organizationId;
@property (nonatomic, retain, getter=organizationName, setter=setOrganizationName:) NSString * organizationName;
@property (nonatomic, retain, getter=website, setter=setWebsite:) NSString * website;
@property (nonatomic, retain, getter=logo, setter=setLogo:) Aroma_Image * logo;
@property (nonatomic, retain, getter=techStack, setter=setTechStack:) NSString * techStack;
@property (nonatomic, retain, getter=owners, setter=setOwners:) NSMutableArray * owners;
@property (nonatomic, retain, getter=organizationEmail, setter=setOrganizationEmail:) NSString * organizationEmail;
@property (nonatomic, retain, getter=stockMarketSymbol, setter=setStockMarketSymbol:) NSString * stockMarketSymbol;
@property (nonatomic, retain, getter=logoLink, setter=setLogoLink:) NSString * logoLink;
@property (nonatomic, getter=industry, setter=setIndustry:) int industry;
@property (nonatomic, getter=tier, setter=setTier:) int tier;
@property (nonatomic, retain, getter=organizationDescription, setter=setOrganizationDescription:) NSString * organizationDescription;
@property (nonatomic, retain, getter=githubProfile, setter=setGithubProfile:) NSString * githubProfile;
#endif

- (id) init;
- (id) initWithOrganizationId: (Aroma_uuid) organizationId organizationName: (NSString *) organizationName website: (NSString *) website logo: (Aroma_Image *) logo techStack: (NSString *) techStack owners: (NSMutableArray *) owners organizationEmail: (NSString *) organizationEmail stockMarketSymbol: (NSString *) stockMarketSymbol logoLink: (NSString *) logoLink industry: (int) industry tier: (int) tier organizationDescription: (NSString *) organizationDescription githubProfile: (NSString *) githubProfile;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (Aroma_uuid) organizationId;
- (void) setOrganizationId: (Aroma_uuid) organizationId;
#endif
- (BOOL) organizationIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) organizationName;
- (void) setOrganizationName: (NSString *) organizationName;
#endif
- (BOOL) organizationNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) website;
- (void) setWebsite: (NSString *) website;
#endif
- (BOOL) websiteIsSet;

#if !__has_feature(objc_arc)
- (Aroma_Image *) logo;
- (void) setLogo: (Aroma_Image *) logo;
#endif
- (BOOL) logoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) techStack;
- (void) setTechStack: (NSString *) techStack;
#endif
- (BOOL) techStackIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) owners;
- (void) setOwners: (NSMutableArray *) owners;
#endif
- (BOOL) ownersIsSet;

#if !__has_feature(objc_arc)
- (NSString *) organizationEmail;
- (void) setOrganizationEmail: (NSString *) organizationEmail;
#endif
- (BOOL) organizationEmailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) stockMarketSymbol;
- (void) setStockMarketSymbol: (NSString *) stockMarketSymbol;
#endif
- (BOOL) stockMarketSymbolIsSet;

#if !__has_feature(objc_arc)
- (NSString *) logoLink;
- (void) setLogoLink: (NSString *) logoLink;
#endif
- (BOOL) logoLinkIsSet;

#if !__has_feature(objc_arc)
- (int) industry;
- (void) setIndustry: (int) industry;
#endif
- (BOOL) industryIsSet;

#if !__has_feature(objc_arc)
- (int) tier;
- (void) setTier: (int) tier;
#endif
- (BOOL) tierIsSet;

#if !__has_feature(objc_arc)
- (NSString *) organizationDescription;
- (void) setOrganizationDescription: (NSString *) organizationDescription;
#endif
- (BOOL) organizationDescriptionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) githubProfile;
- (void) setGithubProfile: (NSString *) githubProfile;
#endif
- (BOOL) githubProfileIsSet;

@end

@interface Aroma_User : NSObject <TBase, NSCoding> {
  NSString * __email;
  Aroma_uuid __userId;
  NSString * __name;
  NSMutableSet * __roles;
  Aroma_Image * __profileImage;
  Aroma_uuid __profileImageLink;
  NSString * __githubProfile;
  NSString * __firstName;
  NSString * __middleName;
  NSString * __lastName;
  Aroma_timestamp __birthdate;
  Aroma_timestamp __timeUserJoined;

  BOOL __email_isset;
  BOOL __userId_isset;
  BOOL __name_isset;
  BOOL __roles_isset;
  BOOL __profileImage_isset;
  BOOL __profileImageLink_isset;
  BOOL __githubProfile_isset;
  BOOL __firstName_isset;
  BOOL __middleName_isset;
  BOOL __lastName_isset;
  BOOL __birthdate_isset;
  BOOL __timeUserJoined_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=userId, setter=setUserId:) Aroma_uuid userId;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=roles, setter=setRoles:) NSMutableSet * roles;
@property (nonatomic, retain, getter=profileImage, setter=setProfileImage:) Aroma_Image * profileImage;
@property (nonatomic, retain, getter=profileImageLink, setter=setProfileImageLink:) Aroma_uuid profileImageLink;
@property (nonatomic, retain, getter=githubProfile, setter=setGithubProfile:) NSString * githubProfile;
@property (nonatomic, retain, getter=firstName, setter=setFirstName:) NSString * firstName;
@property (nonatomic, retain, getter=middleName, setter=setMiddleName:) NSString * middleName;
@property (nonatomic, retain, getter=lastName, setter=setLastName:) NSString * lastName;
@property (nonatomic, getter=birthdate, setter=setBirthdate:) Aroma_timestamp birthdate;
@property (nonatomic, getter=timeUserJoined, setter=setTimeUserJoined:) Aroma_timestamp timeUserJoined;
#endif

- (id) init;
- (id) initWithEmail: (NSString *) email userId: (Aroma_uuid) userId name: (NSString *) name roles: (NSMutableSet *) roles profileImage: (Aroma_Image *) profileImage profileImageLink: (Aroma_uuid) profileImageLink githubProfile: (NSString *) githubProfile firstName: (NSString *) firstName middleName: (NSString *) middleName lastName: (NSString *) lastName birthdate: (Aroma_timestamp) birthdate timeUserJoined: (Aroma_timestamp) timeUserJoined;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (Aroma_uuid) userId;
- (void) setUserId: (Aroma_uuid) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSMutableSet *) roles;
- (void) setRoles: (NSMutableSet *) roles;
#endif
- (BOOL) rolesIsSet;

#if !__has_feature(objc_arc)
- (Aroma_Image *) profileImage;
- (void) setProfileImage: (Aroma_Image *) profileImage;
#endif
- (BOOL) profileImageIsSet;

#if !__has_feature(objc_arc)
- (Aroma_uuid) profileImageLink;
- (void) setProfileImageLink: (Aroma_uuid) profileImageLink;
#endif
- (BOOL) profileImageLinkIsSet;

#if !__has_feature(objc_arc)
- (NSString *) githubProfile;
- (void) setGithubProfile: (NSString *) githubProfile;
#endif
- (BOOL) githubProfileIsSet;

#if !__has_feature(objc_arc)
- (NSString *) firstName;
- (void) setFirstName: (NSString *) firstName;
#endif
- (BOOL) firstNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) middleName;
- (void) setMiddleName: (NSString *) middleName;
#endif
- (BOOL) middleNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) lastName;
- (void) setLastName: (NSString *) lastName;
#endif
- (BOOL) lastNameIsSet;

#if !__has_feature(objc_arc)
- (Aroma_timestamp) birthdate;
- (void) setBirthdate: (Aroma_timestamp) birthdate;
#endif
- (BOOL) birthdateIsSet;

#if !__has_feature(objc_arc)
- (Aroma_timestamp) timeUserJoined;
- (void) setTimeUserJoined: (Aroma_timestamp) timeUserJoined;
#endif
- (BOOL) timeUserJoinedIsSet;

@end

@interface Aroma_Application : NSObject <TBase, NSCoding> {
  NSMutableSet * __owners;
  Aroma_timestamp __timeOfProvisioning;
  NSString * __name;
  Aroma_uuid __applicationId;
  Aroma_long __totalMessagesSent;
  Aroma_Image * __icon;
  int __programmingLanguage;
  NSMutableSet * __followers;
  NSString * __applicationDescription;
  Aroma_uuid __organizationId;
  int __tier;
  Aroma_timestamp __timeOfTokenExpiration;
  Aroma_uuid __applicationIconMediaId;
  BOOL __isFollowing;

  BOOL __owners_isset;
  BOOL __timeOfProvisioning_isset;
  BOOL __name_isset;
  BOOL __applicationId_isset;
  BOOL __totalMessagesSent_isset;
  BOOL __icon_isset;
  BOOL __programmingLanguage_isset;
  BOOL __followers_isset;
  BOOL __applicationDescription_isset;
  BOOL __organizationId_isset;
  BOOL __tier_isset;
  BOOL __timeOfTokenExpiration_isset;
  BOOL __applicationIconMediaId_isset;
  BOOL __isFollowing_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=owners, setter=setOwners:) NSMutableSet * owners;
@property (nonatomic, getter=timeOfProvisioning, setter=setTimeOfProvisioning:) Aroma_timestamp timeOfProvisioning;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=applicationId, setter=setApplicationId:) Aroma_uuid applicationId;
@property (nonatomic, getter=totalMessagesSent, setter=setTotalMessagesSent:) Aroma_long totalMessagesSent;
@property (nonatomic, retain, getter=icon, setter=setIcon:) Aroma_Image * icon;
@property (nonatomic, getter=programmingLanguage, setter=setProgrammingLanguage:) int programmingLanguage;
@property (nonatomic, retain, getter=followers, setter=setFollowers:) NSMutableSet * followers;
@property (nonatomic, retain, getter=applicationDescription, setter=setApplicationDescription:) NSString * applicationDescription;
@property (nonatomic, retain, getter=organizationId, setter=setOrganizationId:) Aroma_uuid organizationId;
@property (nonatomic, getter=tier, setter=setTier:) int tier;
@property (nonatomic, getter=timeOfTokenExpiration, setter=setTimeOfTokenExpiration:) Aroma_timestamp timeOfTokenExpiration;
@property (nonatomic, retain, getter=applicationIconMediaId, setter=setApplicationIconMediaId:) Aroma_uuid applicationIconMediaId;
@property (nonatomic, getter=isFollowing, setter=setIsFollowing:) BOOL isFollowing;
#endif

- (id) init;
- (id) initWithOwners: (NSMutableSet *) owners timeOfProvisioning: (Aroma_timestamp) timeOfProvisioning name: (NSString *) name applicationId: (Aroma_uuid) applicationId totalMessagesSent: (Aroma_long) totalMessagesSent icon: (Aroma_Image *) icon programmingLanguage: (int) programmingLanguage followers: (NSMutableSet *) followers applicationDescription: (NSString *) applicationDescription organizationId: (Aroma_uuid) organizationId tier: (int) tier timeOfTokenExpiration: (Aroma_timestamp) timeOfTokenExpiration applicationIconMediaId: (Aroma_uuid) applicationIconMediaId isFollowing: (BOOL) isFollowing;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableSet *) owners;
- (void) setOwners: (NSMutableSet *) owners;
#endif
- (BOOL) ownersIsSet;

#if !__has_feature(objc_arc)
- (Aroma_timestamp) timeOfProvisioning;
- (void) setTimeOfProvisioning: (Aroma_timestamp) timeOfProvisioning;
#endif
- (BOOL) timeOfProvisioningIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (Aroma_uuid) applicationId;
- (void) setApplicationId: (Aroma_uuid) applicationId;
#endif
- (BOOL) applicationIdIsSet;

#if !__has_feature(objc_arc)
- (Aroma_long) totalMessagesSent;
- (void) setTotalMessagesSent: (Aroma_long) totalMessagesSent;
#endif
- (BOOL) totalMessagesSentIsSet;

#if !__has_feature(objc_arc)
- (Aroma_Image *) icon;
- (void) setIcon: (Aroma_Image *) icon;
#endif
- (BOOL) iconIsSet;

#if !__has_feature(objc_arc)
- (int) programmingLanguage;
- (void) setProgrammingLanguage: (int) programmingLanguage;
#endif
- (BOOL) programmingLanguageIsSet;

#if !__has_feature(objc_arc)
- (NSMutableSet *) followers;
- (void) setFollowers: (NSMutableSet *) followers;
#endif
- (BOOL) followersIsSet;

#if !__has_feature(objc_arc)
- (NSString *) applicationDescription;
- (void) setApplicationDescription: (NSString *) applicationDescription;
#endif
- (BOOL) applicationDescriptionIsSet;

#if !__has_feature(objc_arc)
- (Aroma_uuid) organizationId;
- (void) setOrganizationId: (Aroma_uuid) organizationId;
#endif
- (BOOL) organizationIdIsSet;

#if !__has_feature(objc_arc)
- (int) tier;
- (void) setTier: (int) tier;
#endif
- (BOOL) tierIsSet;

#if !__has_feature(objc_arc)
- (Aroma_timestamp) timeOfTokenExpiration;
- (void) setTimeOfTokenExpiration: (Aroma_timestamp) timeOfTokenExpiration;
#endif
- (BOOL) timeOfTokenExpirationIsSet;

#if !__has_feature(objc_arc)
- (Aroma_uuid) applicationIconMediaId;
- (void) setApplicationIconMediaId: (Aroma_uuid) applicationIconMediaId;
#endif
- (BOOL) applicationIconMediaIdIsSet;

#if !__has_feature(objc_arc)
- (BOOL) isFollowing;
- (void) setIsFollowing: (BOOL) isFollowing;
#endif
- (BOOL) isFollowingIsSet;

@end

@interface Aroma_ServiceAnnouncement : NSObject <TBase, NSCoding> {
  NSString * __message;
  int __importance;
  Aroma_uuid __id;
  Aroma_timestamp __timeOfExpiration;

  BOOL __message_isset;
  BOOL __importance_isset;
  BOOL __id_isset;
  BOOL __timeOfExpiration_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, getter=importance, setter=setImportance:) int importance;
@property (nonatomic, retain, getter=id, setter=setId:) Aroma_uuid id;
@property (nonatomic, getter=timeOfExpiration, setter=setTimeOfExpiration:) Aroma_timestamp timeOfExpiration;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message importance: (int) importance id: (Aroma_uuid) id timeOfExpiration: (Aroma_timestamp) timeOfExpiration;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (int) importance;
- (void) setImportance: (int) importance;
#endif
- (BOOL) importanceIsSet;

#if !__has_feature(objc_arc)
- (Aroma_uuid) id;
- (void) setId: (Aroma_uuid) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (Aroma_timestamp) timeOfExpiration;
- (void) setTimeOfExpiration: (Aroma_timestamp) timeOfExpiration;
#endif
- (BOOL) timeOfExpirationIsSet;

@end

@interface Aroma_AromaConstants : NSObject {
}
+ (double) API_VERSION;
@end
