/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"

#import "Authentication.h"
#import "Aroma.h"

typedef AromaAuthentication_ApplicationToken * AromaEvents_ApplicationToken;

typedef Aroma_int AromaEvents_int;

typedef Aroma_long AromaEvents_long;

typedef Aroma_timestamp AromaEvents_timestamp;

typedef Aroma_uuid AromaEvents_uuid;

typedef Aroma_User * AromaEvents_User;

typedef Aroma_Application * AromaEvents_Application;

@interface AromaEvents_ApplicationMessagesDeleted : NSObject <TBase, NSCoding> {
  AromaEvents_int __totalMessagesDeleted;
  NSString * __message;

  BOOL __totalMessagesDeleted_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=totalMessagesDeleted, setter=setTotalMessagesDeleted:) AromaEvents_int totalMessagesDeleted;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithTotalMessagesDeleted: (AromaEvents_int) totalMessagesDeleted message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AromaEvents_int) totalMessagesDeleted;
- (void) setTotalMessagesDeleted: (AromaEvents_int) totalMessagesDeleted;
#endif
- (BOOL) totalMessagesDeletedIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_ApplicationTokenRenewed : NSObject <TBase, NSCoding> {
  AromaEvents_ApplicationToken __applicationToken;
  NSString * __message;

  BOOL __applicationToken_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=applicationToken, setter=setApplicationToken:) AromaEvents_ApplicationToken applicationToken;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithApplicationToken: (AromaEvents_ApplicationToken) applicationToken message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationToken) applicationToken;
- (void) setApplicationToken: (AromaEvents_ApplicationToken) applicationToken;
#endif
- (BOOL) applicationTokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_ApplicationTokenRegenerated : NSObject <TBase, NSCoding> {
  AromaEvents_ApplicationToken __applicationToken;
  AromaEvents_User __actor;
  NSString * __message;

  BOOL __applicationToken_isset;
  BOOL __actor_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=applicationToken, setter=setApplicationToken:) AromaEvents_ApplicationToken applicationToken;
@property (nonatomic, retain, getter=actor, setter=setActor:) AromaEvents_User actor;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithApplicationToken: (AromaEvents_ApplicationToken) applicationToken actor: (AromaEvents_User) actor message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationToken) applicationToken;
- (void) setApplicationToken: (AromaEvents_ApplicationToken) applicationToken;
#endif
- (BOOL) applicationTokenIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_User) actor;
- (void) setActor: (AromaEvents_User) actor;
#endif
- (BOOL) actorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_ApplicationSentMessage : NSObject <TBase, NSCoding> {
  AromaEvents_uuid __messageId;
  Aroma_Message * __messageSentByApplication;
  NSString * __message;

  BOOL __messageId_isset;
  BOOL __messageSentByApplication_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=messageId, setter=setMessageId:) AromaEvents_uuid messageId;
@property (nonatomic, retain, getter=messageSentByApplication, setter=setMessageSentByApplication:) Aroma_Message * messageSentByApplication;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessageId: (AromaEvents_uuid) messageId messageSentByApplication: (Aroma_Message *) messageSentByApplication message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AromaEvents_uuid) messageId;
- (void) setMessageId: (AromaEvents_uuid) messageId;
#endif
- (BOOL) messageIdIsSet;

#if !__has_feature(objc_arc)
- (Aroma_Message *) messageSentByApplication;
- (void) setMessageSentByApplication: (Aroma_Message *) messageSentByApplication;
#endif
- (BOOL) messageSentByApplicationIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_ApplicationDeleted : NSObject <TBase, NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_ApplicationFollowed : NSObject <TBase, NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_ApplicationUnfollowed : NSObject <TBase, NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_ApplicationUpdated : NSObject <TBase, NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_ApplicationReactionsUpdated : NSObject <TBase, NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_HealthCheckFailed : NSObject <TBase, NSCoding> {
  NSString * __hostname;
  NSString * __message;

  BOOL __hostname_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=hostname, setter=setHostname:) NSString * hostname;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithHostname: (NSString *) hostname message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) hostname;
- (void) setHostname: (NSString *) hostname;
#endif
- (BOOL) hostnameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_HealthCheckBackToNormal : NSObject <TBase, NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_OwnerAdded : NSObject <TBase, NSCoding> {
  AromaEvents_uuid __userIdOfNewOwner;
  AromaEvents_User __newOwner;
  NSString * __message;

  BOOL __userIdOfNewOwner_isset;
  BOOL __newOwner_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=userIdOfNewOwner, setter=setUserIdOfNewOwner:) AromaEvents_uuid userIdOfNewOwner;
@property (nonatomic, retain, getter=newOwner, setter=setNewOwner:) AromaEvents_User newOwner;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithUserIdOfNewOwner: (AromaEvents_uuid) userIdOfNewOwner newOwner: (AromaEvents_User) newOwner message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AromaEvents_uuid) userIdOfNewOwner;
- (void) setUserIdOfNewOwner: (AromaEvents_uuid) userIdOfNewOwner;
#endif
- (BOOL) userIdOfNewOwnerIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_User) newOwner;
- (void) setNewOwner: (AromaEvents_User) newOwner;
#endif
- (BOOL) newOwnerIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_OwnerApprovedRequest : NSObject <TBase, NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_GeneralEvent : NSObject <TBase, NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface AromaEvents_EventType : NSObject <TBase, NSCoding> {
  AromaEvents_ApplicationMessagesDeleted * __applicationMessageDeleted;
  AromaEvents_HealthCheckFailed * __healthCheckFailed;
  AromaEvents_HealthCheckBackToNormal * __healthCheckBackToNormal;
  AromaEvents_ApplicationFollowed * __applicationFollowed;
  AromaEvents_ApplicationDeleted * __applicationDeleted;
  AromaEvents_ApplicationReactionsUpdated * __applicationReactionsUpdated;
  AromaEvents_ApplicationTokenRenewed * __applicationTokenRenewed;
  AromaEvents_ApplicationTokenRegenerated * __applicationTokenRegenerated;
  AromaEvents_ApplicationSentMessage * __applicationSentMessage;
  AromaEvents_ApplicationUnfollowed * __applicationUnfollowed;
  AromaEvents_ApplicationUpdated * __applicationUpdated;
  AromaEvents_OwnerApprovedRequest * __ownerApprovedRequest;
  AromaEvents_OwnerAdded * __ownerAdded;
  AromaEvents_GeneralEvent * __generalEvent;

  BOOL __applicationMessageDeleted_isset;
  BOOL __healthCheckFailed_isset;
  BOOL __healthCheckBackToNormal_isset;
  BOOL __applicationFollowed_isset;
  BOOL __applicationDeleted_isset;
  BOOL __applicationReactionsUpdated_isset;
  BOOL __applicationTokenRenewed_isset;
  BOOL __applicationTokenRegenerated_isset;
  BOOL __applicationSentMessage_isset;
  BOOL __applicationUnfollowed_isset;
  BOOL __applicationUpdated_isset;
  BOOL __ownerApprovedRequest_isset;
  BOOL __ownerAdded_isset;
  BOOL __generalEvent_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=applicationMessageDeleted, setter=setApplicationMessageDeleted:) AromaEvents_ApplicationMessagesDeleted * applicationMessageDeleted;
@property (nonatomic, retain, getter=healthCheckFailed, setter=setHealthCheckFailed:) AromaEvents_HealthCheckFailed * healthCheckFailed;
@property (nonatomic, retain, getter=healthCheckBackToNormal, setter=setHealthCheckBackToNormal:) AromaEvents_HealthCheckBackToNormal * healthCheckBackToNormal;
@property (nonatomic, retain, getter=applicationFollowed, setter=setApplicationFollowed:) AromaEvents_ApplicationFollowed * applicationFollowed;
@property (nonatomic, retain, getter=applicationDeleted, setter=setApplicationDeleted:) AromaEvents_ApplicationDeleted * applicationDeleted;
@property (nonatomic, retain, getter=applicationReactionsUpdated, setter=setApplicationReactionsUpdated:) AromaEvents_ApplicationReactionsUpdated * applicationReactionsUpdated;
@property (nonatomic, retain, getter=applicationTokenRenewed, setter=setApplicationTokenRenewed:) AromaEvents_ApplicationTokenRenewed * applicationTokenRenewed;
@property (nonatomic, retain, getter=applicationTokenRegenerated, setter=setApplicationTokenRegenerated:) AromaEvents_ApplicationTokenRegenerated * applicationTokenRegenerated;
@property (nonatomic, retain, getter=applicationSentMessage, setter=setApplicationSentMessage:) AromaEvents_ApplicationSentMessage * applicationSentMessage;
@property (nonatomic, retain, getter=applicationUnfollowed, setter=setApplicationUnfollowed:) AromaEvents_ApplicationUnfollowed * applicationUnfollowed;
@property (nonatomic, retain, getter=applicationUpdated, setter=setApplicationUpdated:) AromaEvents_ApplicationUpdated * applicationUpdated;
@property (nonatomic, retain, getter=ownerApprovedRequest, setter=setOwnerApprovedRequest:) AromaEvents_OwnerApprovedRequest * ownerApprovedRequest;
@property (nonatomic, retain, getter=ownerAdded, setter=setOwnerAdded:) AromaEvents_OwnerAdded * ownerAdded;
@property (nonatomic, retain, getter=generalEvent, setter=setGeneralEvent:) AromaEvents_GeneralEvent * generalEvent;
#endif

- (id) init;
- (id) initWithApplicationMessageDeleted: (AromaEvents_ApplicationMessagesDeleted *) applicationMessageDeleted healthCheckFailed: (AromaEvents_HealthCheckFailed *) healthCheckFailed healthCheckBackToNormal: (AromaEvents_HealthCheckBackToNormal *) healthCheckBackToNormal applicationFollowed: (AromaEvents_ApplicationFollowed *) applicationFollowed applicationDeleted: (AromaEvents_ApplicationDeleted *) applicationDeleted applicationReactionsUpdated: (AromaEvents_ApplicationReactionsUpdated *) applicationReactionsUpdated applicationTokenRenewed: (AromaEvents_ApplicationTokenRenewed *) applicationTokenRenewed applicationTokenRegenerated: (AromaEvents_ApplicationTokenRegenerated *) applicationTokenRegenerated applicationSentMessage: (AromaEvents_ApplicationSentMessage *) applicationSentMessage applicationUnfollowed: (AromaEvents_ApplicationUnfollowed *) applicationUnfollowed applicationUpdated: (AromaEvents_ApplicationUpdated *) applicationUpdated ownerApprovedRequest: (AromaEvents_OwnerApprovedRequest *) ownerApprovedRequest ownerAdded: (AromaEvents_OwnerAdded *) ownerAdded generalEvent: (AromaEvents_GeneralEvent *) generalEvent;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationMessagesDeleted *) applicationMessageDeleted;
- (void) setApplicationMessageDeleted: (AromaEvents_ApplicationMessagesDeleted *) applicationMessageDeleted;
#endif
- (BOOL) applicationMessageDeletedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_HealthCheckFailed *) healthCheckFailed;
- (void) setHealthCheckFailed: (AromaEvents_HealthCheckFailed *) healthCheckFailed;
#endif
- (BOOL) healthCheckFailedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_HealthCheckBackToNormal *) healthCheckBackToNormal;
- (void) setHealthCheckBackToNormal: (AromaEvents_HealthCheckBackToNormal *) healthCheckBackToNormal;
#endif
- (BOOL) healthCheckBackToNormalIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationFollowed *) applicationFollowed;
- (void) setApplicationFollowed: (AromaEvents_ApplicationFollowed *) applicationFollowed;
#endif
- (BOOL) applicationFollowedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationDeleted *) applicationDeleted;
- (void) setApplicationDeleted: (AromaEvents_ApplicationDeleted *) applicationDeleted;
#endif
- (BOOL) applicationDeletedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationReactionsUpdated *) applicationReactionsUpdated;
- (void) setApplicationReactionsUpdated: (AromaEvents_ApplicationReactionsUpdated *) applicationReactionsUpdated;
#endif
- (BOOL) applicationReactionsUpdatedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationTokenRenewed *) applicationTokenRenewed;
- (void) setApplicationTokenRenewed: (AromaEvents_ApplicationTokenRenewed *) applicationTokenRenewed;
#endif
- (BOOL) applicationTokenRenewedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationTokenRegenerated *) applicationTokenRegenerated;
- (void) setApplicationTokenRegenerated: (AromaEvents_ApplicationTokenRegenerated *) applicationTokenRegenerated;
#endif
- (BOOL) applicationTokenRegeneratedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationSentMessage *) applicationSentMessage;
- (void) setApplicationSentMessage: (AromaEvents_ApplicationSentMessage *) applicationSentMessage;
#endif
- (BOOL) applicationSentMessageIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationUnfollowed *) applicationUnfollowed;
- (void) setApplicationUnfollowed: (AromaEvents_ApplicationUnfollowed *) applicationUnfollowed;
#endif
- (BOOL) applicationUnfollowedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_ApplicationUpdated *) applicationUpdated;
- (void) setApplicationUpdated: (AromaEvents_ApplicationUpdated *) applicationUpdated;
#endif
- (BOOL) applicationUpdatedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_OwnerApprovedRequest *) ownerApprovedRequest;
- (void) setOwnerApprovedRequest: (AromaEvents_OwnerApprovedRequest *) ownerApprovedRequest;
#endif
- (BOOL) ownerApprovedRequestIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_OwnerAdded *) ownerAdded;
- (void) setOwnerAdded: (AromaEvents_OwnerAdded *) ownerAdded;
#endif
- (BOOL) ownerAddedIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_GeneralEvent *) generalEvent;
- (void) setGeneralEvent: (AromaEvents_GeneralEvent *) generalEvent;
#endif
- (BOOL) generalEventIsSet;

@end

@interface AromaEvents_Event : NSObject <TBase, NSCoding> {
  AromaEvents_uuid __eventId;
  AromaEvents_uuid __userIdOfActor;
  AromaEvents_User __actor;
  AromaEvents_uuid __applicationId;
  AromaEvents_Application __application;
  AromaEvents_EventType * __eventType;
  AromaEvents_timestamp __timestamp;

  BOOL __eventId_isset;
  BOOL __userIdOfActor_isset;
  BOOL __actor_isset;
  BOOL __applicationId_isset;
  BOOL __application_isset;
  BOOL __eventType_isset;
  BOOL __timestamp_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=eventId, setter=setEventId:) AromaEvents_uuid eventId;
@property (nonatomic, retain, getter=userIdOfActor, setter=setUserIdOfActor:) AromaEvents_uuid userIdOfActor;
@property (nonatomic, retain, getter=actor, setter=setActor:) AromaEvents_User actor;
@property (nonatomic, retain, getter=applicationId, setter=setApplicationId:) AromaEvents_uuid applicationId;
@property (nonatomic, retain, getter=application, setter=setApplication:) AromaEvents_Application application;
@property (nonatomic, retain, getter=eventType, setter=setEventType:) AromaEvents_EventType * eventType;
@property (nonatomic, getter=timestamp, setter=setTimestamp:) AromaEvents_timestamp timestamp;
#endif

- (id) init;
- (id) initWithEventId: (AromaEvents_uuid) eventId userIdOfActor: (AromaEvents_uuid) userIdOfActor actor: (AromaEvents_User) actor applicationId: (AromaEvents_uuid) applicationId application: (AromaEvents_Application) application eventType: (AromaEvents_EventType *) eventType timestamp: (AromaEvents_timestamp) timestamp;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AromaEvents_uuid) eventId;
- (void) setEventId: (AromaEvents_uuid) eventId;
#endif
- (BOOL) eventIdIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_uuid) userIdOfActor;
- (void) setUserIdOfActor: (AromaEvents_uuid) userIdOfActor;
#endif
- (BOOL) userIdOfActorIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_User) actor;
- (void) setActor: (AromaEvents_User) actor;
#endif
- (BOOL) actorIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_uuid) applicationId;
- (void) setApplicationId: (AromaEvents_uuid) applicationId;
#endif
- (BOOL) applicationIdIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_Application) application;
- (void) setApplication: (AromaEvents_Application) application;
#endif
- (BOOL) applicationIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_EventType *) eventType;
- (void) setEventType: (AromaEvents_EventType *) eventType;
#endif
- (BOOL) eventTypeIsSet;

#if !__has_feature(objc_arc)
- (AromaEvents_timestamp) timestamp;
- (void) setTimestamp: (AromaEvents_timestamp) timestamp;
#endif
- (BOOL) timestampIsSet;

@end

@interface AromaEvents_EventsConstants : NSObject {
}
@end
